#!/usr/bin/env python3
"""Plot the Accuracy vs EOD Pareto frontier.
Requested by Reviewer 2: "the proposed method does not perform strongly enough compared
with the benchmarks... is there a Pareto frontier?"

Usage:
    python -m qevc.scripts.pareto_plot --dataset vqacp
"""

import argparse
import json
from pathlib import Path
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser(description="Plot Accuracy vs EOD Pareto Frontier")
    parser.add_argument("--dataset", choices=["vqacp", "mimic"], default="vqacp")
    args = parser.parse_args()

    results_dir = Path("qevc/results")
    
    # 1. Load baselines
    baselines_path = results_dir / f"baselines_{args.dataset}.json"
    points = []
    
    if baselines_path.exists():
        with open(baselines_path) as f:
            baselines = json.load(f)
        for name, metrics in baselines.items():
            if isinstance(metrics, dict) and "accuracy" in metrics and "eod" in metrics:
                # AdvDeb might have EOD=0.0 due to divergence (degenerate)
                # But we plot it anyway
                points.append({
                    "name": name.upper(),
                    "acc": metrics["accuracy"],
                    "eod": metrics["eod"],
                    "type": "baseline"
                })

    # Fallback to binary results if available (from local files)
    binary_eval = Path("files/eval_vqacp_binary.json")
    if args.dataset == "vqacp" and binary_eval.exists():
        print(f"Loading binary eval fallback: {binary_eval}")
        with open(binary_eval) as f:
            data = json.load(f)
            for k in ["mlp", "svm"]:
                if k in data:
                    points.append({
                        "name": k.upper(),
                        "acc": data[k]["test_accuracy"],
                        "eod": data[k]["eod"],
                        "type": "baseline"
                    })
            if "qevc" in data:
                points.append({
                    "name": "QEVC (Ours)",
                    "acc": data["qevc"]["test_accuracy"],
                    "eod": data["qevc"]["eod"],
                    "type": "qevc"
                })

    # 2. Load QEVC single eval
    eval_path = results_dir / f"eval_{args.dataset}.json"
    if eval_path.exists():
        with open(eval_path) as f:
            metrics = json.load(f)
        points.append({
            "name": "QEVC (Ours)",
            "acc": metrics["accuracy"],
            "eod": metrics["eod"],
            "type": "qevc"
        })

    # 3. Load Ablations to show the frontier trade-off
    ablation_path = results_dir / "ablation" / f"ablation_summary_{args.dataset}.json"
    if ablation_path.exists():
        # Note: the current ablation_summary just has return codes, the actual
        # eval metrics would ideally be generated by validate_qfs.py saving them.
        # But for the plot we could plot multiple QEVC lambda variants.
        pass

    # Deduplicate points by name
    unique_points = {p["name"]: p for p in points}.values()
    points = list(unique_points)

    if not points:
        print("No results found to plot. Run evaluation and baselines first.")
        return

    # Create plot
    plt.figure(figsize=(8, 6))
    
    # We want HIGH accuracy (right) and LOW EOD (bottom), so ideal is bottom-right.
    # Standard Pareto is usually upper-left if both are to be maximized.
    # To make standard Pareto visualization, let's plot EOD vs Accuracy.
    
    for p in points:
        color = "red" if p["type"] == "qevc" else "blue"
        marker = "star" if p["type"] == "qevc" else "o"
        size = 200 if p["type"] == "qevc" else 100
        
        plt.scatter(p["eod"], p["acc"], c=color, s=size, label=p["name"], edgecolors="k", zorder=5)
        plt.annotate(
            p["name"],
            (p["eod"], p["acc"]),
            xytext=(8, 5),
            textcoords="offset points",
            fontweight="bold" if p["type"] == "qevc" else "normal"
        )

    plt.xlabel("Equalized Odds Difference (EOD) ↓ Better", fontsize=12)
    plt.ylabel("Accuracy ↑ Better", fontsize=12)
    plt.title(f"Accuracy-Fairness Trade-off ({args.dataset.upper()})", fontsize=14)
    plt.grid(True, linestyle="--", alpha=0.6, zorder=0)
    
    # Invert X axis so that "better" (lower EOD) is on the right, making the
    # top-right corner the ideal zone
    plt.xlim(max(p["eod"] for p in points) + 0.05, -0.05)
    
    # Save
    out_path = results_dir / f"pareto_{args.dataset}.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    print(f"Plot saved to {out_path}")


if __name__ == "__main__":
    main()
